/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import enlighten.monitoring.models.BatteryDeviceTelemetryIntervalsInner
import enlighten.monitoring.models.TelemetryGranularityEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param systemId System ID.
 * @param serialNumber Device serial number.
 * @param granularity 
 * @param totalDevices Shall always be 1 since this is telemetry from individual micros.
 * @param startAt Start time of the data series. Either start_date or start_at will be present. By default start_at will appear in response. If start_date parameter passed in the url then start_date field will appear in response.
 * @param endAt End time of the data series. Either end_date or end_at will be present. By default end_at will appear in response. If end_date parameter passed in the url then end_date field will appear in response.
 * @param items List key 'intervals'.
 * @param intervals 
 * @param lastReportedTime Last reported timestamp.
 * @param lastReportedSoc Last reported soc percentage.
 */


data class BatteryDeviceTelemetry (

    /* System ID. */
    @Json(name = "system_id")
    val systemId: kotlin.Int? = null,

    /* Device serial number. */
    @Json(name = "serial_number")
    val serialNumber: kotlin.String? = null,

    @Json(name = "granularity")
    val granularity: TelemetryGranularityEnum? = null,

    /* Shall always be 1 since this is telemetry from individual micros. */
    @Json(name = "total_devices")
    val totalDevices: kotlin.Int? = null,

    /* Start time of the data series. Either start_date or start_at will be present. By default start_at will appear in response. If start_date parameter passed in the url then start_date field will appear in response. */
    @Json(name = "start_at")
    val startAt: kotlin.Long? = null,

    /* End time of the data series. Either end_date or end_at will be present. By default end_at will appear in response. If end_date parameter passed in the url then end_date field will appear in response. */
    @Json(name = "end_at")
    val endAt: kotlin.Long? = null,

    /* List key 'intervals'. */
    @Json(name = "items")
    val items: kotlin.String? = null,

    @Json(name = "intervals")
    val intervals: kotlin.collections.List<BatteryDeviceTelemetryIntervalsInner>? = null,

    /* Last reported timestamp. */
    @Json(name = "last_reported_time")
    val lastReportedTime: kotlin.Int? = null,

    /* Last reported soc percentage. */
    @Json(name = "last_reported_soc")
    val lastReportedSoc: kotlin.String? = null

)

