/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param details Error details.
 * @param code Error code.
 * @param message Error type.
 */


data class ClientError (

    /* Error details. */
    @Json(name = "details")
    val details: kotlin.String,

    /* Error code. */
    @Json(name = "code")
    val code: kotlin.Int,

    /* Error type. */
    @Json(name = "message")
    val message: kotlin.String? = null

)

