/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import enlighten.monitoring.models.GetInvertersSummaryByEnvoyOrSiteResponseInnerMicroInvertersInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param signalStrength Signal strength.
 * @param microInverters Microinverters.
 */


data class GetInvertersSummaryByEnvoyOrSiteResponseInner (

    /* Signal strength. */
    @Json(name = "signal_strength")
    val signalStrength: kotlin.Int? = null,

    /* Microinverters. */
    @Json(name = "micro_inverters")
    val microInverters: kotlin.collections.List<GetInvertersSummaryByEnvoyOrSiteResponseInnerMicroInvertersInner>? = null

)

