/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `value` Lifetime energy produced by the microinverter.
 * @param units Energy units.
 * @param precision 
 */


data class GetInvertersSummaryByEnvoyOrSiteResponseInnerMicroInvertersInnerEnergy (

    /* Lifetime energy produced by the microinverter. */
    @Json(name = "value")
    val `value`: kotlin.Int? = null,

    /* Energy units. */
    @Json(name = "units")
    val units: kotlin.String? = null,

    @Json(name = "precision")
    val precision: kotlin.Int? = null

)

