/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param endAt End time of the telemetry interval.
 * @param devicesReporting Number of devices reporting.
 * @param enwh Units produced per interval.
 */


data class GetSystemConsumptionMeterTelemetryResponseIntervalsInner (

    /* End time of the telemetry interval. */
    @Json(name = "end_at")
    val endAt: kotlin.Long? = null,

    /* Number of devices reporting. */
    @Json(name = "devices_reporting")
    val devicesReporting: kotlin.Int? = null,

    /* Units produced per interval. */
    @Json(name = "enwh")
    val enwh: kotlin.Int? = null

)

