/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import enlighten.monitoring.models.Meta

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param systemId Unique numeric ID of the system.
 * @param startDate When no start_date parameter is specified on the request, defaults to the operational_date of the system. May be null if system has never produced. When a start_date parameter is included in the request, the same is included in the response.
 * @param consumption An array of consumption measurements in Wh, one for each day since consumption metering began, or one for each day of the requested period.
 * @param meta 
 */


data class GetSystemConsumptionLifetimeResponse (

    /* Unique numeric ID of the system. */
    @Json(name = "system_id")
    val systemId: kotlin.Int? = null,

    /* When no start_date parameter is specified on the request, defaults to the operational_date of the system. May be null if system has never produced. When a start_date parameter is included in the request, the same is included in the response. */
    @Json(name = "start_date")
    val startDate: java.time.LocalDate? = null,

    /* An array of consumption measurements in Wh, one for each day since consumption metering began, or one for each day of the requested period. */
    @Json(name = "consumption")
    val consumption: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "meta")
    val meta: Meta? = null

)

