/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import enlighten.monitoring.models.DataTemporarilyUnavailableError
import enlighten.monitoring.models.InternalServerError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param reason 
 * @param message 
 * @param errorCode Error code.
 * @param errorMessages Error messages.
 */


data class GetSystems500Response (

    @Json(name = "reason")
    val reason: kotlin.String? = null,

    @Json(name = "message")
    val message: kotlin.collections.List<kotlin.String>? = null,

    /* Error code. */
    @Json(name = "errorCode")
    val errorCode: kotlin.Int? = null,

    /* Error messages. */
    @Json(name = "errorMessages")
    val errorMessages: kotlin.collections.List<kotlin.String>? = null

)

