/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param imei 
 * @param partNum 
 * @param sku 
 * @param planStartDate 
 * @param planEndDate 
 */


data class GetSystemDevicesResponseDevicesValueInnerCellularModem (

    @Json(name = "imei")
    val imei: kotlin.String? = null,

    @Json(name = "part_num")
    val partNum: kotlin.String? = null,

    @Json(name = "sku")
    val sku: kotlin.String? = null,

    @Json(name = "plan_start_date")
    val planStartDate: kotlin.Long? = null,

    @Json(name = "plan_end_date")
    val planEndDate: kotlin.Long? = null

)

