/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import enlighten.monitoring.models.GetSystemBatteryTelemetryResponseIntervalsInnerCharge
import enlighten.monitoring.models.GetSystemBatteryTelemetryResponseIntervalsInnerDischarge
import enlighten.monitoring.models.GetSystemBatteryTelemetryResponseIntervalsInnerSoc

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param endAt End time of the telemetry interval.
 * @param charge 
 * @param discharge 
 * @param soc 
 */


data class GetSystemBatteryTelemetryResponseIntervalsInner (

    /* End time of the telemetry interval. */
    @Json(name = "end_at")
    val endAt: kotlin.Long? = null,

    @Json(name = "charge")
    val charge: GetSystemBatteryTelemetryResponseIntervalsInnerCharge? = null,

    @Json(name = "discharge")
    val discharge: GetSystemBatteryTelemetryResponseIntervalsInnerDischarge? = null,

    @Json(name = "soc")
    val soc: GetSystemBatteryTelemetryResponseIntervalsInnerSoc? = null

)

