/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import enlighten.monitoring.models.GetSystemDevicesResponseDevicesValueInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param systemId System ID.
 * @param totalDevices Total active devices associated with the system.
 * @param items List key.
 * @param devices Hash keys include all the possible device types micros, meters, gateways, mids, q_relays, ACBs, Encharges, Enpowers (if the devices of this type are present). For all the device types, the object will contain the serial_number and model with some additional information pertaining to the device type.
 */


data class GetSystemDevicesResponse (

    /* System ID. */
    @Json(name = "system_id")
    val systemId: kotlin.Int? = null,

    /* Total active devices associated with the system. */
    @Json(name = "total_devices")
    val totalDevices: kotlin.Int? = null,

    /* List key. */
    @Json(name = "items")
    val items: kotlin.String? = null,

    /* Hash keys include all the possible device types micros, meters, gateways, mids, q_relays, ACBs, Encharges, Enpowers (if the devices of this type are present). For all the device types, the object will contain the serial_number and model with some additional information pertaining to the device type. */
    @Json(name = "devices")
    val devices: kotlin.collections.Map<kotlin.String, kotlin.collections.List<GetSystemDevicesResponseDevicesValueInner>>? = null

)

