/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import enlighten.monitoring.models.SystemStatusEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Information about the system such as its status, when it became operational and last reported to Envoy.
 *
 * @param status 
 * @param lastReportAt Timestamp (in epoch format) at which the system's Envoy last submitted a report.
 * @param lastEnergyAt Timestamp (in epoch format) at which the system's produced energy was last reported. Even if the last produced energy is 0, its timestamp will be returned.
 * @param operationalAt Timestamp (in epoch format) at which this system became operational. Corresponds to the system's interconnect time, if one is specified. Otherwise, it is the system's first reported interval end time.
 */


data class Meta (

    @Json(name = "status")
    val status: SystemStatusEnum? = null,

    /* Timestamp (in epoch format) at which the system's Envoy last submitted a report. */
    @Json(name = "last_report_at")
    val lastReportAt: kotlin.Int? = null,

    /* Timestamp (in epoch format) at which the system's produced energy was last reported. Even if the last produced energy is 0, its timestamp will be returned. */
    @Json(name = "last_energy_at")
    val lastEnergyAt: kotlin.Int? = null,

    /* Timestamp (in epoch format) at which this system became operational. Corresponds to the system's interconnect time, if one is specified. Otherwise, it is the system's first reported interval end time. */
    @Json(name = "operational_at")
    val operationalAt: kotlin.Int? = null

)

