/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import enlighten.monitoring.models.SearchSystemsRequestSystem
import enlighten.monitoring.models.SystemSortByEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param system 
 * @param sortBy 
 */


data class SearchSystemsRequest (

    @Json(name = "system")
    val system: SearchSystemsRequestSystem,

    @Json(name = "sort_by")
    val sortBy: SystemSortByEnum? = null

)

