/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param systemId 
 * @param stormGuardStatus Overrides your battery profile to full backup mode when a severe weather condition alert is issued in the locality.
 * @param stormAlert True if severe weather condition alert is issued in the locality.
 */


data class StormGuardSettings (

    @Json(name = "system_id")
    val systemId: kotlin.Int? = null,

    /* Overrides your battery profile to full backup mode when a severe weather condition alert is issued in the locality. */
    @Json(name = "storm_guard_status")
    val stormGuardStatus: kotlin.String? = null,

    /* True if severe weather condition alert is issued in the locality. */
    @Json(name = "storm_alert")
    val stormAlert: kotlin.Boolean? = null

)

