/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param code 
 * @param details 
 * @param message 
 * @param status 
 */


data class StreamSystemLiveDataErrorError (

    @Json(name = "code")
    val code: kotlin.Int? = null,

    @Json(name = "details")
    val details: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "status")
    val status: kotlin.String? = null

)

