/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Name displayed on the public system page. Default=residential. Only for systems that allow public access.
 *
 * Values: residential,all,commercial,other
 */

@JsonClass(generateAdapter = false)
enum class SystemPublicNameEnum(val value: kotlin.String) {

    @Json(name = "residential")
    residential("residential"),

    @Json(name = "all")
    all("all"),

    @Json(name = "commercial")
    commercial("commercial"),

    @Json(name = "other")
    other("other");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SystemPublicNameEnum) "$data" else null

        /**
         * Returns a valid [SystemPublicNameEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SystemPublicNameEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

