/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Returns list of systems sorted by <sort_by> field. To get ASC order sorted list, user sort_by = <key>. To get DESC order sorted list, use sort_by = (-)<key>. Current sort keys supported are id, name, and last_report_date. By default the list is sorted by decreasing system ID.
 *
 * Values: id,name,last_report_date,MinusId,MinusName,MinusLast_report_date
 */

@JsonClass(generateAdapter = false)
enum class SystemSortByEnum(val value: kotlin.String) {

    @Json(name = "id")
    id("id"),

    @Json(name = "name")
    name("name"),

    @Json(name = "last_report_date")
    last_report_date("last_report_date"),

    @Json(name = "-id")
    MinusId("-id"),

    @Json(name = "-name")
    MinusName("-name"),

    @Json(name = "-last_report_date")
    MinusLast_report_date("-last_report_date");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SystemSortByEnum) "$data" else null

        /**
         * Returns a valid [SystemSortByEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SystemSortByEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

