/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param message Error type.
 * @param details Error details.
 * @param code Error code.
 * @param period Quota exceeded for minute/month.
 * @param periodStart Starting period timestamp.
 * @param periodEnd Ending period timestamp.
 * @param limit Limit count for the period.
 */


data class TooManyRequestsError (

    /* Error type. */
    @Json(name = "message")
    val message: kotlin.String? = null,

    /* Error details. */
    @Json(name = "details")
    val details: kotlin.String? = null,

    /* Error code. */
    @Json(name = "code")
    val code: kotlin.Int? = null,

    /* Quota exceeded for minute/month. */
    @Json(name = "period")
    val period: kotlin.String? = null,

    /* Starting period timestamp. */
    @Json(name = "period_start")
    val periodStart: kotlin.Int? = null,

    /* Ending period timestamp. */
    @Json(name = "period_end")
    val periodEnd: kotlin.Int? = null,

    /* Limit count for the period. */
    @Json(name = "limit")
    val limit: kotlin.Int? = null

)

