/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param stormGuardStatus Overrides your battery profile to full backup mode when a severe weather condition alert is issued in the locality. Available values are enabled, disabled.
 */


data class UpdateSystemStormGuardSettingsRequest (

    /* Overrides your battery profile to full backup mode when a severe weather condition alert is issued in the locality. Available values are enabled, disabled. */
    @Json(name = "storm_guard_status")
    val stormGuardStatus: kotlin.String

)

