/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param batteryMode To update battery mode of the system (case sensitive). Available values are Savings Mode, Self-consumption, Full Backup.
 * @param reserveSoc Reserve soc for the current mode. Cannot be less than vls.
 * @param energyIndependence Energy independence after peak hours \"enabled\"/\"disabled\". Enabled: Battery will discharge to save money during peak hours when electricity rates are high. Once that is done, energy independence is prioritized. This will increase the energy self-sufficiency until the reserve soc is hit. Battery will charge from solar in the morning to get ready for the next period. Disabled: Battery will discharge only during peak hours when electricity rates are high. During other times, battery will be idle or will charge from solar in the morning to get ready for the next period.
 */


data class UpdateSystemBatterySettingsRequest (

    /* To update battery mode of the system (case sensitive). Available values are Savings Mode, Self-consumption, Full Backup. */
    @Json(name = "battery_mode")
    val batteryMode: kotlin.String? = null,

    /* Reserve soc for the current mode. Cannot be less than vls. */
    @Json(name = "reserve_soc")
    val reserveSoc: kotlin.Int? = null,

    /* Energy independence after peak hours \"enabled\"/\"disabled\". Enabled: Battery will discharge to save money during peak hours when electricity rates are high. Once that is done, energy independence is prioritized. This will increase the energy self-sufficiency until the reserve soc is hit. Battery will charge from solar in the morning to get ready for the next period. Disabled: Battery will discharge only during peak hours when electricity rates are high. During other times, battery will be idle or will charge from solar in the morning to get ready for the next period. */
    @Json(name = "energy_independence")
    val energyIndependence: kotlin.String? = null

)

