/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.models.ConsumptionStatsResponseIntervalsInner

class ConsumptionStatsResponseIntervalsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConsumptionStatsResponseIntervalsInner
        //val modelInstance = ConsumptionStatsResponseIntervalsInner()

        // to test the property `endAt` - End of interval. The format is Unix epoch time unless you pass a `datetime_format` parameter as described [here](https://developer.enphase.com/docs#Datetimes).
        should("test endAt") {
            // uncomment below to test the property
            //modelInstance.endAt shouldBe ("TODO")
        }

        // to test the property `enwh` - Energy consumed during this interval, in Watt-hours.
        should("test enwh") {
            // uncomment below to test the property
            //modelInstance.enwh shouldBe ("TODO")
        }

        // to test the property `devicesReporting` - Number of consumption meters that reported data for this interval at the time of the request.
        should("test devicesReporting") {
            // uncomment below to test the property
            //modelInstance.devicesReporting shouldBe ("TODO")
        }

    }
}
