/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.models.InventoryResponseEnvoysInner

class InventoryResponseEnvoysInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InventoryResponseEnvoysInner
        //val modelInstance = InventoryResponseEnvoysInner()

        // to test the property `sn`
        should("test sn") {
            // uncomment below to test the property
            //modelInstance.sn shouldBe ("TODO")
        }

        // to test the property `model`
        should("test model") {
            // uncomment below to test the property
            //modelInstance.model shouldBe ("TODO")
        }

        // to test the property `sku`
        should("test sku") {
            // uncomment below to test the property
            //modelInstance.sku shouldBe ("TODO")
        }

    }
}
