/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.models.Meta
import enlighten.models.Status

class MetaTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Meta
        //val modelInstance = Meta()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `lastReportAt`
        should("test lastReportAt") {
            // uncomment below to test the property
            //modelInstance.lastReportAt shouldBe ("TODO")
        }

        // to test the property `lastEnergyAt`
        should("test lastEnergyAt") {
            // uncomment below to test the property
            //modelInstance.lastEnergyAt shouldBe ("TODO")
        }

        // to test the property `operationalAt`
        should("test operationalAt") {
            // uncomment below to test the property
            //modelInstance.operationalAt shouldBe ("TODO")
        }

    }
}
