/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.models.ProductionMeterReadingsResponse
import enlighten.models.Meta
import enlighten.models.ProductionMeterReadingsResponseMeterReadingsInner

class ProductionMeterReadingsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductionMeterReadingsResponse
        //val modelInstance = ProductionMeterReadingsResponse()

        // to test the property `systemId`
        should("test systemId") {
            // uncomment below to test the property
            //modelInstance.systemId shouldBe ("TODO")
        }

        // to test the property `meterReadings`
        should("test meterReadings") {
            // uncomment below to test the property
            //modelInstance.meterReadings shouldBe ("TODO")
        }

        // to test the property `meta`
        should("test meta") {
            // uncomment below to test the property
            //modelInstance.meta shouldBe ("TODO")
        }

    }
}
