/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.models.ProductionMeterReadingsResponseMeterReadingsInner

class ProductionMeterReadingsResponseMeterReadingsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductionMeterReadingsResponseMeterReadingsInner
        //val modelInstance = ProductionMeterReadingsResponseMeterReadingsInner()

        // to test the property `serialNumber` - The serial number of the meter.
        should("test serialNumber") {
            // uncomment below to test the property
            //modelInstance.serialNumber shouldBe ("TODO")
        }

        // to test the property ``value`` - The odometer reading, in Watt-hours.
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `readAt` - The time when the reading was taken, always prior or equal to the requested `end_at`.
        should("test readAt") {
            // uncomment below to test the property
            //modelInstance.readAt shouldBe ("TODO")
        }

    }
}
