/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.models.SystemsResponse
import enlighten.models.SystemsResponseSystemsInner

class SystemsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemsResponse
        //val modelInstance = SystemsResponse()

        // to test the property `systems`
        should("test systems") {
            // uncomment below to test the property
            //modelInstance.systems shouldBe ("TODO")
        }

        // to test the property `next`
        should("test next") {
            // uncomment below to test the property
            //modelInstance.next shouldBe ("TODO")
        }

    }
}
