/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param reason 
 * @param message 
 * @param period 
 * @param periodStart 
 * @param periodEnd 
 * @param limit 
 */


data class ConflictError (

    @Json(name = "reason")
    val reason: kotlin.String,

    @Json(name = "message")
    val message: kotlin.collections.List<kotlin.String>,

    @Json(name = "period")
    val period: ConflictError.Period,

    @Json(name = "period_start")
    val periodStart: kotlin.Int,

    @Json(name = "period_end")
    val periodEnd: kotlin.Int,

    @Json(name = "limit")
    val limit: kotlin.Int

) {

    /**
     * 
     *
     * Values: hour,minute,second
     */
    @JsonClass(generateAdapter = false)
    enum class Period(val value: kotlin.String) {
        @Json(name = "hour") hour("hour"),
        @Json(name = "minute") minute("minute"),
        @Json(name = "second") second("second");
    }
}

