/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param envoyId The Enlighten ID of the Envoy.
 * @param lastReportAt The last time this Envoy submitted a report, by default expressed in Unix epoch time. When the `datetime_format` query parameter is `iso8601`, `last_report_at` is in ISO 8601 format. If Enlighten has no record of a report from this Envoy, returns null.
 * @param name The human-friendly name of this Envoy.
 * @param partNumber The Enphase part number of this Envoy.
 * @param serialNumber The serial number of this Envoy.
 * @param status The current status of this Envoy. * `normal` - The Envoy is operating normally. * `comm` - The Envoy is not communicating to Enlighten.
 */


data class EnvoysResponseEnvoysInner (

    /* The Enlighten ID of the Envoy. */
    @Json(name = "envoy_id")
    val envoyId: kotlin.Int,

    /* The last time this Envoy submitted a report, by default expressed in Unix epoch time. When the `datetime_format` query parameter is `iso8601`, `last_report_at` is in ISO 8601 format. If Enlighten has no record of a report from this Envoy, returns null. */
    @Json(name = "last_report_at")
    val lastReportAt: kotlin.Long,

    /* The human-friendly name of this Envoy. */
    @Json(name = "name")
    val name: kotlin.String,

    /* The Enphase part number of this Envoy. */
    @Json(name = "part_number")
    val partNumber: kotlin.String,

    /* The serial number of this Envoy. */
    @Json(name = "serial_number")
    val serialNumber: kotlin.String,

    /* The current status of this Envoy. * `normal` - The Envoy is operating normally. * `comm` - The Envoy is not communicating to Enlighten. */
    @Json(name = "status")
    val status: EnvoysResponseEnvoysInner.Status

) {

    /**
     * The current status of this Envoy. * `normal` - The Envoy is operating normally. * `comm` - The Envoy is not communicating to Enlighten.
     *
     * Values: normal,comm
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "normal") normal("normal"),
        @Json(name = "comm") comm("comm");
    }
}

