/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.models

import enlighten.models.InventoryResponseEnvoysInner
import enlighten.models.InventoryResponseMetersInner
import enlighten.models.Meta

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param systemId Enlighten ID for this system.
 * @param inverters A list of inverters on this system, including serial and model numbers.
 * @param meters A list of meters on this system, including serial number, manufacturer, and model number.
 * @param meta 
 * @param envoys A list of Envoys on this system, including serial number.
 */


data class InventoryResponse (

    /* Enlighten ID for this system. */
    @Json(name = "system_id")
    val systemId: kotlin.Int,

    /* A list of inverters on this system, including serial and model numbers. */
    @Json(name = "inverters")
    val inverters: kotlin.collections.List<InventoryResponseEnvoysInner>,

    /* A list of meters on this system, including serial number, manufacturer, and model number. */
    @Json(name = "meters")
    val meters: kotlin.collections.List<InventoryResponseMetersInner>,

    @Json(name = "meta")
    val meta: Meta,

    /* A list of Envoys on this system, including serial number. */
    @Json(name = "envoys")
    val envoys: kotlin.collections.List<InventoryResponseEnvoysInner>? = null

)

