/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.models

import enlighten.models.Status

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Information about the system that you can use to ascertain the timeliness of the production data included in the response.
 *
 * @param status 
 * @param lastReportAt 
 * @param lastEnergyAt 
 * @param operationalAt 
 */


data class Meta (

    @Json(name = "status")
    val status: Status,

    @Json(name = "last_report_at")
    val lastReportAt: kotlin.Long,

    @Json(name = "last_energy_at")
    val lastEnergyAt: kotlin.Long,

    @Json(name = "operational_at")
    val operationalAt: kotlin.Long

)

