/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param serialNumber 
 * @param start 
 * @param end 
 */


data class MonthlyProductionResponseMeterReadingsInner (

    @Json(name = "serial_number")
    val serialNumber: kotlin.String,

    @Json(name = "start")
    val start: kotlin.Int,

    @Json(name = "end")
    val end: kotlin.Int

)

