/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.models

import enlighten.models.Meta
import enlighten.models.MonthlyProductionResponseMeterReadingsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param systemId Enlighten ID for this system.
 * @param startDate First day included in the reporting period. The format is `YYYY-mm-dd` unless you pass a `datetime_format` parameter as described [here](https://developer.enphase.com/docs#Datetimes).
 * @param endDate Last day included in the reporting period.
 * @param productionWh Total production for the requested period in Watt-hours.
 * @param meterReadings If the system has any revenue-grade meters installed, the meter readings at the beginning and end of the reporting period are included here. Otherwise, the array is empty.
 * @param meta 
 */


data class MonthlyProductionResponse (

    /* Enlighten ID for this system. */
    @Json(name = "system_id")
    val systemId: kotlin.Int,

    /* First day included in the reporting period. The format is `YYYY-mm-dd` unless you pass a `datetime_format` parameter as described [here](https://developer.enphase.com/docs#Datetimes). */
    @Json(name = "start_date")
    val startDate: java.time.LocalDate,

    /* Last day included in the reporting period. */
    @Json(name = "end_date")
    val endDate: java.time.LocalDate,

    /* Total production for the requested period in Watt-hours. */
    @Json(name = "production_wh")
    val productionWh: kotlin.Int,

    /* If the system has any revenue-grade meters installed, the meter readings at the beginning and end of the reporting period are included here. Otherwise, the array is empty. */
    @Json(name = "meter_readings")
    val meterReadings: kotlin.collections.List<MonthlyProductionResponseMeterReadingsInner>,

    @Json(name = "meta")
    val meta: Meta

)

