/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param serialNumber The serial number of the meter.
 * @param `value` The odometer reading, in Watt-hours.
 * @param readAt The time when the reading was taken, always prior or equal to the requested `end_at`.
 */


data class ProductionMeterReadingsResponseMeterReadingsInner (

    /* The serial number of the meter. */
    @Json(name = "serial_number")
    val serialNumber: kotlin.String,

    /* The odometer reading, in Watt-hours. */
    @Json(name = "value")
    val `value`: kotlin.Int,

    /* The time when the reading was taken, always prior or equal to the requested `end_at`. */
    @Json(name = "read_at")
    val readAt: kotlin.Long

)

