/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.models

import enlighten.models.RgmStatsResponseMeterIntervalsInnerIntervalsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param meterSerialNumber Serial number of the revenue grade meter.
 * @param envoySerialNumber Serial number of the reporting envoy.
 * @param intervals Individual meter level interval.
 */


data class RgmStatsResponseMeterIntervalsInner (

    /* Serial number of the revenue grade meter. */
    @Json(name = "meter_serial_number")
    val meterSerialNumber: kotlin.String,

    /* Serial number of the reporting envoy. */
    @Json(name = "envoy_serial_number")
    val envoySerialNumber: kotlin.String,

    /* Individual meter level interval. */
    @Json(name = "intervals")
    val intervals: kotlin.collections.List<RgmStatsResponseMeterIntervalsInnerIntervalsInner>

)

