/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.BatterySettings

class BatterySettingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BatterySettings
        //val modelInstance = BatterySettings()

        // to test the property `systemId`
        should("test systemId") {
            // uncomment below to test the property
            //modelInstance.systemId shouldBe ("TODO")
        }

        // to test the property `batteryMode` - Current battery mode of the system. Available values are Savings Mode, Full Backup, and Self - Consumption.
        should("test batteryMode") {
            // uncomment below to test the property
            //modelInstance.batteryMode shouldBe ("TODO")
        }

        // to test the property `reserveSoc` - Reserve soc for the current mode.
        should("test reserveSoc") {
            // uncomment below to test the property
            //modelInstance.reserveSoc shouldBe ("TODO")
        }

        // to test the property `energyIndependence` - Energy independence after peak hours enabled/disabled. Enabled: Battery will discharge to save money during peak hours when electricity rates are high. Once that is done, energy independence is prioritized. This will increase the energy self-sufficiency until the reserve soc is hit. Battery will charge from solar in the morning to get ready for the next period. Disabled: Battery will discharge only during peak hours when electricity rates are high. During other times, battery will be idle or will charge from solar in the morning to get ready for the next period.
        should("test energyIndependence") {
            // uncomment below to test the property
            //modelInstance.energyIndependence shouldBe ("TODO")
        }

        // to test the property `chargeFromGrid` - Charge battery from grid enabled/disabled. Enabled: Battery may also charge from the grid when in full backup mode or when battery charge is below the reserve capacity in savings or self-consumption mode.
        should("test chargeFromGrid") {
            // uncomment below to test the property
            //modelInstance.chargeFromGrid shouldBe ("TODO")
        }

        // to test the property `batteryShutdownLevel` - Level at which battery shutdowns to conserve energy. Battery restarts by using the conserved energy when the utility grid restores power or solar panels start producing energy.
        should("test batteryShutdownLevel") {
            // uncomment below to test the property
            //modelInstance.batteryShutdownLevel shouldBe ("TODO")
        }

    }
}
