/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.BatteryDeviceTelemetryIntervalsInnerDischarge

class BatteryDeviceTelemetryIntervalsInnerDischargeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BatteryDeviceTelemetryIntervalsInnerDischarge
        //val modelInstance = BatteryDeviceTelemetryIntervalsInnerDischarge()

        // to test the property `enwh` - Energy discharged from the battery during the interval.
        should("test enwh") {
            // uncomment below to test the property
            //modelInstance.enwh shouldBe ("TODO")
        }

    }
}
