/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.BatteryDeviceTelemetryIntervalsInnerSoc

class BatteryDeviceTelemetryIntervalsInnerSocTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BatteryDeviceTelemetryIntervalsInnerSoc
        //val modelInstance = BatteryDeviceTelemetryIntervalsInnerSoc()

        // to test the property `percent` - Battery soc percentage.
        should("test percent") {
            // uncomment below to test the property
            //modelInstance.percent shouldBe ("TODO")
        }

    }
}
