/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.BatteryDeviceTelemetryIntervalsInner
import enlighten.monitoring.models.BatteryDeviceTelemetryIntervalsInnerCharge
import enlighten.monitoring.models.BatteryDeviceTelemetryIntervalsInnerDischarge
import enlighten.monitoring.models.BatteryDeviceTelemetryIntervalsInnerSoc

class BatteryDeviceTelemetryIntervalsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BatteryDeviceTelemetryIntervalsInner
        //val modelInstance = BatteryDeviceTelemetryIntervalsInner()

        // to test the property `endAt` - End time of the telemetry interval.
        should("test endAt") {
            // uncomment below to test the property
            //modelInstance.endAt shouldBe ("TODO")
        }

        // to test the property `charge`
        should("test charge") {
            // uncomment below to test the property
            //modelInstance.charge shouldBe ("TODO")
        }

        // to test the property `discharge`
        should("test discharge") {
            // uncomment below to test the property
            //modelInstance.discharge shouldBe ("TODO")
        }

        // to test the property `soc`
        should("test soc") {
            // uncomment below to test the property
            //modelInstance.soc shouldBe ("TODO")
        }

    }
}
