/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.GetInvertersSummaryByEnvoyOrSiteResponseInnerMicroInvertersInnerEnergy

class GetInvertersSummaryByEnvoyOrSiteResponseInnerMicroInvertersInnerEnergyTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetInvertersSummaryByEnvoyOrSiteResponseInnerMicroInvertersInnerEnergy
        //val modelInstance = GetInvertersSummaryByEnvoyOrSiteResponseInnerMicroInvertersInnerEnergy()

        // to test the property ``value`` - Lifetime energy produced by the microinverter.
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `units` - Energy units.
        should("test units") {
            // uncomment below to test the property
            //modelInstance.units shouldBe ("TODO")
        }

        // to test the property `precision`
        should("test precision") {
            // uncomment below to test the property
            //modelInstance.precision shouldBe ("TODO")
        }

    }
}
