/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.GetInvertersSummaryByEnvoyOrSiteResponseInner
import enlighten.monitoring.models.GetInvertersSummaryByEnvoyOrSiteResponseInnerMicroInvertersInner

class GetInvertersSummaryByEnvoyOrSiteResponseInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetInvertersSummaryByEnvoyOrSiteResponseInner
        //val modelInstance = GetInvertersSummaryByEnvoyOrSiteResponseInner()

        // to test the property `signalStrength` - Signal strength.
        should("test signalStrength") {
            // uncomment below to test the property
            //modelInstance.signalStrength shouldBe ("TODO")
        }

        // to test the property `microInverters` - Microinverters.
        should("test microInverters") {
            // uncomment below to test the property
            //modelInstance.microInverters shouldBe ("TODO")
        }

    }
}
