/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.GetSystemDevicesResponseDevicesValueInner
import enlighten.monitoring.models.GetSystemDevicesResponseDevicesValueInnerCellularModem

class GetSystemDevicesResponseDevicesValueInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetSystemDevicesResponseDevicesValueInner
        //val modelInstance = GetSystemDevicesResponseDevicesValueInner()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `lastReportAt`
        should("test lastReportAt") {
            // uncomment below to test the property
            //modelInstance.lastReportAt shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `serialNumber`
        should("test serialNumber") {
            // uncomment below to test the property
            //modelInstance.serialNumber shouldBe ("TODO")
        }

        // to test the property `partNumber`
        should("test partNumber") {
            // uncomment below to test the property
            //modelInstance.partNumber shouldBe ("TODO")
        }

        // to test the property `emuSwVersion`
        should("test emuSwVersion") {
            // uncomment below to test the property
            //modelInstance.emuSwVersion shouldBe ("TODO")
        }

        // to test the property `sku`
        should("test sku") {
            // uncomment below to test the property
            //modelInstance.sku shouldBe ("TODO")
        }

        // to test the property `model`
        should("test model") {
            // uncomment below to test the property
            //modelInstance.model shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `active`
        should("test active") {
            // uncomment below to test the property
            //modelInstance.active shouldBe ("TODO")
        }

        // to test the property `state`
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `configType`
        should("test configType") {
            // uncomment below to test the property
            //modelInstance.configType shouldBe ("TODO")
        }

        // to test the property `cellularModem`
        should("test cellularModem") {
            // uncomment below to test the property
            //modelInstance.cellularModem shouldBe ("TODO")
        }

    }
}
