/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.GetSystemBatteryTelemetryResponseIntervalsInnerCharge

class GetSystemBatteryTelemetryResponseIntervalsInnerChargeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetSystemBatteryTelemetryResponseIntervalsInnerCharge
        //val modelInstance = GetSystemBatteryTelemetryResponseIntervalsInnerCharge()

        // to test the property `enwh` - Energy into the battery during the interval.
        should("test enwh") {
            // uncomment below to test the property
            //modelInstance.enwh shouldBe ("TODO")
        }

        // to test the property `devicesReporting` - Number of devices reporting.
        should("test devicesReporting") {
            // uncomment below to test the property
            //modelInstance.devicesReporting shouldBe ("TODO")
        }

    }
}
