/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.GetSystemGridStatusSettingsResponse

class GetSystemGridStatusSettingsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetSystemGridStatusSettingsResponse
        //val modelInstance = GetSystemGridStatusSettingsResponse()

        // to test the property `systemId`
        should("test systemId") {
            // uncomment below to test the property
            //modelInstance.systemId shouldBe ("TODO")
        }

        // to test the property `gridState` - Indicates whether the site is On Grid, Off Grid or grid status of site is Unknown.
        should("test gridState") {
            // uncomment below to test the property
            //modelInstance.gridState shouldBe ("TODO")
        }

        // to test the property `lastReportDate` - Timestamp (in epoch format) at which the system's Envoy last submitted a report.
        should("test lastReportDate") {
            // uncomment below to test the property
            //modelInstance.lastReportDate shouldBe ("TODO")
        }

    }
}
