/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.GetSystemRgmStatsResponse
import enlighten.monitoring.models.GetSystemRgmStatsResponseIntervalsInner
import enlighten.monitoring.models.GetSystemRgmStatsResponseMeterIntervalsInner
import enlighten.monitoring.models.Meta

class GetSystemRgmStatsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetSystemRgmStatsResponse
        //val modelInstance = GetSystemRgmStatsResponse()

        // to test the property `systemId` - System ID.
        should("test systemId") {
            // uncomment below to test the property
            //modelInstance.systemId shouldBe ("TODO")
        }

        // to test the property `totalDevices` - Number of active revenue-grade meters for this system.
        should("test totalDevices") {
            // uncomment below to test the property
            //modelInstance.totalDevices shouldBe ("TODO")
        }

        // to test the property `meta`
        should("test meta") {
            // uncomment below to test the property
            //modelInstance.meta shouldBe ("TODO")
        }

        // to test the property `intervals` - A list of intervals between the requested start and end times.
        should("test intervals") {
            // uncomment below to test the property
            //modelInstance.intervals shouldBe ("TODO")
        }

        // to test the property `meterIntervals` - A list of intervals of a meter between the requested start and end times.
        should("test meterIntervals") {
            // uncomment below to test the property
            //modelInstance.meterIntervals shouldBe ("TODO")
        }

    }
}
