/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.GetSystemRgmStatsResponseIntervalsInner

class GetSystemRgmStatsResponseIntervalsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetSystemRgmStatsResponseIntervalsInner
        //val modelInstance = GetSystemRgmStatsResponseIntervalsInner()

        // to test the property `endAt` - End time of the telemetry interval.
        should("test endAt") {
            // uncomment below to test the property
            //modelInstance.endAt shouldBe ("TODO")
        }

        // to test the property `devicesReporting` - Number of revenue-grade meters that reported data for this interval at the time of the request.
        should("test devicesReporting") {
            // uncomment below to test the property
            //modelInstance.devicesReporting shouldBe ("TODO")
        }

        // to test the property `whDel` - Energy delivered during this interval, in Wh.
        should("test whDel") {
            // uncomment below to test the property
            //modelInstance.whDel shouldBe ("TODO")
        }

    }
}
