/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.GetSystemDevicesResponseDevicesValueInnerCellularModem

class GetSystemDevicesResponseDevicesValueInnerCellularModemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetSystemDevicesResponseDevicesValueInnerCellularModem
        //val modelInstance = GetSystemDevicesResponseDevicesValueInnerCellularModem()

        // to test the property `imei`
        should("test imei") {
            // uncomment below to test the property
            //modelInstance.imei shouldBe ("TODO")
        }

        // to test the property `partNum`
        should("test partNum") {
            // uncomment below to test the property
            //modelInstance.partNum shouldBe ("TODO")
        }

        // to test the property `sku`
        should("test sku") {
            // uncomment below to test the property
            //modelInstance.sku shouldBe ("TODO")
        }

        // to test the property `planStartDate`
        should("test planStartDate") {
            // uncomment below to test the property
            //modelInstance.planStartDate shouldBe ("TODO")
        }

        // to test the property `planEndDate`
        should("test planEndDate") {
            // uncomment below to test the property
            //modelInstance.planEndDate shouldBe ("TODO")
        }

    }
}
