/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.GetSystemConsumptionLifetimeResponse
import enlighten.monitoring.models.Meta

class GetSystemConsumptionLifetimeResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetSystemConsumptionLifetimeResponse
        //val modelInstance = GetSystemConsumptionLifetimeResponse()

        // to test the property `systemId` - Unique numeric ID of the system.
        should("test systemId") {
            // uncomment below to test the property
            //modelInstance.systemId shouldBe ("TODO")
        }

        // to test the property `startDate` - When no start_date parameter is specified on the request, defaults to the operational_date of the system. May be null if system has never produced. When a start_date parameter is included in the request, the same is included in the response.
        should("test startDate") {
            // uncomment below to test the property
            //modelInstance.startDate shouldBe ("TODO")
        }

        // to test the property `consumption` - An array of consumption measurements in Wh, one for each day since consumption metering began, or one for each day of the requested period.
        should("test consumption") {
            // uncomment below to test the property
            //modelInstance.consumption shouldBe ("TODO")
        }

        // to test the property `meta`
        should("test meta") {
            // uncomment below to test the property
            //modelInstance.meta shouldBe ("TODO")
        }

    }
}
