/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.SearchSystemsResponse
import enlighten.monitoring.models.SystemDetails

class SearchSystemsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchSystemsResponse
        //val modelInstance = SearchSystemsResponse()

        // to test the property `total` - Total number of systems available.
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `currentPage` - Current page of the systems result. Default is 1.
        should("test currentPage") {
            // uncomment below to test the property
            //modelInstance.currentPage shouldBe ("TODO")
        }

        // to test the property `propertySize` - Max number of records from API per page is 100. Default is 10.
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

        // to test the property `count` - Total number of systems actually returned for the current page.
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `items` - Named key of the list data. In this endpoint, it is systems.
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

        // to test the property `systems` - List of filtered systems.
        should("test systems") {
            // uncomment below to test the property
            //modelInstance.systems shouldBe ("TODO")
        }

    }
}
