/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.SearchSystemsRequest
import enlighten.monitoring.models.SearchSystemsRequestSystem
import enlighten.monitoring.models.SystemSortByEnum

class SearchSystemsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchSystemsRequest
        //val modelInstance = SearchSystemsRequest()

        // to test the property `system`
        should("test system") {
            // uncomment below to test the property
            //modelInstance.system shouldBe ("TODO")
        }

        // to test the property `sortBy`
        should("test sortBy") {
            // uncomment below to test the property
            //modelInstance.sortBy shouldBe ("TODO")
        }

    }
}
