/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.StormGuardSettings

class StormGuardSettingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StormGuardSettings
        //val modelInstance = StormGuardSettings()

        // to test the property `systemId`
        should("test systemId") {
            // uncomment below to test the property
            //modelInstance.systemId shouldBe ("TODO")
        }

        // to test the property `stormGuardStatus` - Overrides your battery profile to full backup mode when a severe weather condition alert is issued in the locality.
        should("test stormGuardStatus") {
            // uncomment below to test the property
            //modelInstance.stormGuardStatus shouldBe ("TODO")
        }

        // to test the property `stormAlert` - True if severe weather condition alert is issued in the locality.
        should("test stormAlert") {
            // uncomment below to test the property
            //modelInstance.stormAlert shouldBe ("TODO")
        }

    }
}
