/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.SystemStatusEnum

class SystemStatusEnumTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemStatusEnum
        //val modelInstance = SystemStatusEnum()

    }
}
