/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.monitoring.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.monitoring.models.TooManyRequestsError

class TooManyRequestsErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TooManyRequestsError
        //val modelInstance = TooManyRequestsError()

        // to test the property `message` - Error type.
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `details` - Error details.
        should("test details") {
            // uncomment below to test the property
            //modelInstance.details shouldBe ("TODO")
        }

        // to test the property `code` - Error code.
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `period` - Quota exceeded for minute/month.
        should("test period") {
            // uncomment below to test the property
            //modelInstance.period shouldBe ("TODO")
        }

        // to test the property `periodStart` - Starting period timestamp.
        should("test periodStart") {
            // uncomment below to test the property
            //modelInstance.periodStart shouldBe ("TODO")
        }

        // to test the property `periodEnd` - Ending period timestamp.
        should("test periodEnd") {
            // uncomment below to test the property
            //modelInstance.periodEnd shouldBe ("TODO")
        }

        // to test the property `limit` - Limit count for the period.
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

    }
}
