/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.apis.GridProfilesApi
import enlighten.commissioning.models.GetGridProfilesResponse
import enlighten.commissioning.models.ServerError
import enlighten.commissioning.models.TooManyRequestsError

class GridProfilesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GridProfilesApi
        //val apiInstance = GridProfilesApi()

        // to test getGridProfiles
        should("test getGridProfiles") {
            // uncomment below to test getGridProfiles
            //val result : GetGridProfilesResponse = apiInstance.getGridProfiles()
            //result shouldBe ("TODO")
        }

    }
}
