/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.apis.PvManufacturersApi
import enlighten.commissioning.models.GetPvManufacturersResponse
import enlighten.commissioning.models.ServerError
import enlighten.commissioning.models.TooManyRequestsError

class PvManufacturersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PvManufacturersApi
        //val apiInstance = PvManufacturersApi()

        // to test getPvManufacturers
        should("test getPvManufacturers") {
            // uncomment below to test getPvManufacturers
            //val result : GetPvManufacturersResponse = apiInstance.getPvManufacturers()
            //result shouldBe ("TODO")
        }

    }
}
