/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.apis.TariffApi
import enlighten.commissioning.models.ServerError
import enlighten.commissioning.models.TariffSettings
import enlighten.commissioning.models.TooManyRequestsError
import enlighten.commissioning.models.UpdateSystemTariffSettingsResponse

class TariffApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TariffApi
        //val apiInstance = TariffApi()

        // to test getSystemTariffSettings
        should("test getSystemTariffSettings") {
            // uncomment below to test getSystemTariffSettings
            //val systemId : kotlin.Int = 56 // kotlin.Int | Unique numeric ID of the system.
            //val result : TariffSettings = apiInstance.getSystemTariffSettings(systemId)
            //result shouldBe ("TODO")
        }

        // to test updateSystemTariffSettings
        should("test updateSystemTariffSettings") {
            // uncomment below to test updateSystemTariffSettings
            //val systemId : kotlin.Int = 56 // kotlin.Int | Unique numeric ID of the system.
            //val params : TariffSettings =  // TariffSettings | 
            //val result : UpdateSystemTariffSettingsResponse = apiInstance.updateSystemTariffSettings(systemId, params)
            //result shouldBe ("TODO")
        }

    }
}
