/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.ActivationEnchargeInner

class ActivationEnchargeInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActivationEnchargeInner
        //val modelInstance = ActivationEnchargeInner()

        // to test the property `envoySerialNumber` - Envoy serial number.
        should("test envoySerialNumber") {
            // uncomment below to test the property
            //modelInstance.envoySerialNumber shouldBe ("TODO")
        }

        // to test the property `enchargeSerialNumbers` - Encharge serial numbers.
        should("test enchargeSerialNumbers") {
            // uncomment below to test the property
            //modelInstance.enchargeSerialNumbers shouldBe ("TODO")
        }

    }
}
