/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.Address

class AddressTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Address
        //val modelInstance = Address()

        // to test the property `street1` - Street line 1.
        should("test street1") {
            // uncomment below to test the property
            //modelInstance.street1 shouldBe ("TODO")
        }

        // to test the property `street2` - Street line 2. This field is optional.
        should("test street2") {
            // uncomment below to test the property
            //modelInstance.street2 shouldBe ("TODO")
        }

        // to test the property `city` - City.
        should("test city") {
            // uncomment below to test the property
            //modelInstance.city shouldBe ("TODO")
        }

        // to test the property `state` - State.
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `country` - Country.
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `postalCode` - Postal code.
        should("test postalCode") {
            // uncomment below to test the property
            //modelInstance.postalCode shouldBe ("TODO")
        }

        // to test the property `latitude` - Latitude.
        should("test latitude") {
            // uncomment below to test the property
            //modelInstance.latitude shouldBe ("TODO")
        }

        // to test the property `longitude` - Longitude.
        should("test longitude") {
            // uncomment below to test the property
            //modelInstance.longitude shouldBe ("TODO")
        }

    }
}
