/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.GetCompanyUsersResponse
import enlighten.commissioning.models.GetCompanyUsersResponseUsersInner

class GetCompanyUsersResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetCompanyUsersResponse
        //val modelInstance = GetCompanyUsersResponse()

        // to test the property `users` - Zero or more users. Each user is an array. In that first value of the array is Enlighten ID of the user. System-generated. Second value of the array is the email address of the user.
        should("test users") {
            // uncomment below to test the property
            //modelInstance.users shouldBe ("TODO")
        }

    }
}
