/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.GetGridProfilesResponseGridProfilesInner

class GetGridProfilesResponseGridProfilesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetGridProfilesResponseGridProfilesInner
        //val modelInstance = GetGridProfilesResponseGridProfilesInner()

        // to test the property `id` - Grid profile ID. System-generated.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `profileId`
        should("test profileId") {
            // uncomment below to test the property
            //modelInstance.profileId shouldBe ("TODO")
        }

        // to test the property `created` - Profile created date and time.
        should("test created") {
            // uncomment below to test the property
            //modelInstance.created shouldBe ("TODO")
        }

        // to test the property `updated` - Profile last updated date and time.
        should("test updated") {
            // uncomment below to test the property
            //modelInstance.updated shouldBe ("TODO")
        }

        // to test the property `name` - Profile name.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description` - Profile description.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `version` - Profile version.
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `envoyType` - Envoy type.
        should("test envoyType") {
            // uncomment below to test the property
            //modelInstance.envoyType shouldBe ("TODO")
        }

        // to test the property `countries` - Name of the Countries.
        should("test countries") {
            // uncomment below to test the property
            //modelInstance.countries shouldBe ("TODO")
        }

        // to test the property `states` - States code.
        should("test states") {
            // uncomment below to test the property
            //modelInstance.states shouldBe ("TODO")
        }

        // to test the property `stateNames` - Name of the states.
        should("test stateNames") {
            // uncomment below to test the property
            //modelInstance.stateNames shouldBe ("TODO")
        }

        // to test the property `ensemble1Compatible`
        should("test ensemble1Compatible") {
            // uncomment below to test the property
            //modelInstance.ensemble1Compatible shouldBe ("TODO")
        }

    }
}
