/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.GetSelfCompanyBranchesResponseBranchesInner
import enlighten.commissioning.models.CompanyRoleEnum

class GetSelfCompanyBranchesResponseBranchesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetSelfCompanyBranchesResponseBranchesInner
        //val modelInstance = GetSelfCompanyBranchesResponseBranchesInner()

        // to test the property `companyId` - Enlighten ID of the company.
        should("test companyId") {
            // uncomment below to test the property
            //modelInstance.companyId shouldBe ("TODO")
        }

        // to test the property `companyName` - Name of the company.
        should("test companyName") {
            // uncomment below to test the property
            //modelInstance.companyName shouldBe ("TODO")
        }

        // to test the property `location` - Company location.
        should("test location") {
            // uncomment below to test the property
            //modelInstance.location shouldBe ("TODO")
        }

        // to test the property `roles` - What type of company this is in Enphase. For installer company roles will be ['installer']. For other role roles will be empty.
        should("test roles") {
            // uncomment below to test the property
            //modelInstance.roles shouldBe ("TODO")
        }

        // to test the property `uri` - URI to the show() method for the company. System-generated.
        should("test uri") {
            // uncomment below to test the property
            //modelInstance.uri shouldBe ("TODO")
        }

    }
}
