/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.SetActivationMeterStatusRequest
import enlighten.commissioning.models.SystemMeterStatusEnum

class SetActivationMeterStatusRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SetActivationMeterStatusRequest
        //val modelInstance = SetActivationMeterStatusRequest()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
