/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.SystemEstimate

class SystemEstimateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemEstimate
        //val modelInstance = SystemEstimate()

        // to test the property `systemId` - System this estimate is for.
        should("test systemId") {
            // uncomment below to test the property
            //modelInstance.systemId shouldBe ("TODO")
        }

        // to test the property `degradeFactor` - Annual production degradation factor for the system, from year 0 of the system's life. Must be 0.0% or higher. Default 0.5%.
        should("test degradeFactor") {
            // uncomment below to test the property
            //modelInstance.degradeFactor shouldBe ("TODO")
        }

        // to test the property `monthEstimates` - Estimated monthly production of the system, in kWh. A value for each month must be provided, and must be greater than 0. Send an empty array if you need to remove monthly estimates. Default empty array.
        should("test monthEstimates") {
            // uncomment below to test the property
            //modelInstance.monthEstimates shouldBe ("TODO")
        }

    }
}
