/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.SystemArraysLayersInner

class SystemArraysLayersInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemArraysLayersInner
        //val modelInstance = SystemArraysLayersInner()

        // to test the property `file` - Background image url.
        should("test file") {
            // uncomment below to test the property
            //modelInstance.file shouldBe ("TODO")
        }

        // to test the property `scale` - Zoom level.
        should("test scale") {
            // uncomment below to test the property
            //modelInstance.scale shouldBe ("TODO")
        }

        // to test the property `angle` - Angle of the layer.
        should("test angle") {
            // uncomment below to test the property
            //modelInstance.angle shouldBe ("TODO")
        }

        // to test the property `opacity` - Opacity of the layer.
        should("test opacity") {
            // uncomment below to test the property
            //modelInstance.opacity shouldBe ("TODO")
        }

        // to test the property `width` - Width of the layer.
        should("test width") {
            // uncomment below to test the property
            //modelInstance.width shouldBe ("TODO")
        }

        // to test the property `height` - Height of the layer.
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

        // to test the property `left` - Left of the layer.
        should("test left") {
            // uncomment below to test the property
            //modelInstance.left shouldBe ("TODO")
        }

        // to test the property `top` - Top of the layer.
        should("test top") {
            // uncomment below to test the property
            //modelInstance.top shouldBe ("TODO")
        }

    }
}
