/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.SystemArrays
import enlighten.commissioning.models.SystemArray
import enlighten.commissioning.models.SystemArraysInventoryDetailsInner
import enlighten.commissioning.models.SystemArraysLayersInner

class SystemArraysTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemArrays
        //val modelInstance = SystemArrays()

        // to test the property `systemId` - System ID.
        should("test systemId") {
            // uncomment below to test the property
            //modelInstance.systemId shouldBe ("TODO")
        }

        // to test the property `createdAt` - System created Epoch time.
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt` - System updated Epoch time.
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `angle` - Angle of the system.
        should("test angle") {
            // uncomment below to test the property
            //modelInstance.angle shouldBe ("TODO")
        }

        // to test the property `arrays`
        should("test arrays") {
            // uncomment below to test the property
            //modelInstance.arrays shouldBe ("TODO")
        }

        // to test the property `inventory` - List of active inverter serial numbers.
        should("test inventory") {
            // uncomment below to test the property
            //modelInstance.inventory shouldBe ("TODO")
        }

        // to test the property `inventoryDetails`
        should("test inventoryDetails") {
            // uncomment below to test the property
            //modelInstance.inventoryDetails shouldBe ("TODO")
        }

        // to test the property `layers`
        should("test layers") {
            // uncomment below to test the property
            //modelInstance.layers shouldBe ("TODO")
        }

    }
}
