/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.SystemArrayModulesInner

class SystemArrayModulesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemArrayModulesInner
        //val modelInstance = SystemArrayModulesInner()

        // to test the property `id` - ID of the module.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `left` - Left axis position of module.
        should("test left") {
            // uncomment below to test the property
            //modelInstance.left shouldBe ("TODO")
        }

        // to test the property `top` - Top axis position of module.
        should("test top") {
            // uncomment below to test the property
            //modelInstance.top shouldBe ("TODO")
        }

        // to test the property `angle` - Angle of the module.
        should("test angle") {
            // uncomment below to test the property
            //modelInstance.angle shouldBe ("TODO")
        }

        // to test the property `serialNum` - Inverter serial number mapped with this module.
        should("test serialNum") {
            // uncomment below to test the property
            //modelInstance.serialNum shouldBe ("TODO")
        }

    }
}
