/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.SystemArraysInventoryDetailsInner

class SystemArraysInventoryDetailsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemArraysInventoryDetailsInner
        //val modelInstance = SystemArraysInventoryDetailsInner()

        // to test the property `type` - Device type.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `count` - Device count.
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `serialNum` - Device serial number.
        should("test serialNum") {
            // uncomment below to test the property
            //modelInstance.serialNum shouldBe ("TODO")
        }

    }
}
