/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.TariffSeasonsInner
import enlighten.commissioning.models.TariffSeasonsInnerDaysInner

class TariffSeasonsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TariffSeasonsInner
        //val modelInstance = TariffSeasonsInner()

        // to test the property `id` - ToU year ID. e.g='all_year_long'.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `start` - Start of season. e.g='1/1'.
        should("test start") {
            // uncomment below to test the property
            //modelInstance.start shouldBe ("TODO")
        }

        // to test the property `days` - ToU seasons.
        should("test days") {
            // uncomment below to test the property
            //modelInstance.days shouldBe ("TODO")
        }

        // to test the property `enableChargeFromGrid`
        should("test enableChargeFromGrid") {
            // uncomment below to test the property
            //modelInstance.enableChargeFromGrid shouldBe ("TODO")
        }

        // to test the property `enableDischargeToGrid`
        should("test enableDischargeToGrid") {
            // uncomment below to test the property
            //modelInstance.enableDischargeToGrid shouldBe ("TODO")
        }

    }
}
