/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.TariffSeasonsInnerDaysInner
import enlighten.commissioning.models.TariffSeasonsInnerDaysInnerPeriodsInner

class TariffSeasonsInnerDaysInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TariffSeasonsInnerDaysInner
        //val modelInstance = TariffSeasonsInnerDaysInner()

        // to test the property `id` - ToU days ID. e.g='all_days'.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `days` - Comma separated days. e.g='Sun,Mon,Tue,Wed,Thu,Fri,Sat'.
        should("test days") {
            // uncomment below to test the property
            //modelInstance.days shouldBe ("TODO")
        }

        // to test the property `mustChargeStart` - Must charge start field. e.g=0.
        should("test mustChargeStart") {
            // uncomment below to test the property
            //modelInstance.mustChargeStart shouldBe ("TODO")
        }

        // to test the property `mustChargeDuration` - Must charge duration field. e.g=0.
        should("test mustChargeDuration") {
            // uncomment below to test the property
            //modelInstance.mustChargeDuration shouldBe ("TODO")
        }

        // to test the property `periods` - Periods.
        should("test periods") {
            // uncomment below to test the property
            //modelInstance.periods shouldBe ("TODO")
        }

    }
}
