/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.TariffSeasonsInnerDaysInnerPeriodsInner

class TariffSeasonsInnerDaysInnerPeriodsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TariffSeasonsInnerDaysInnerPeriodsInner
        //val modelInstance = TariffSeasonsInnerDaysInnerPeriodsInner()

        // to test the property `id` - Period ID. e.g='period_1'.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `start` - Period start. e.g=0.
        should("test start") {
            // uncomment below to test the property
            //modelInstance.start shouldBe ("TODO")
        }

        // to test the property `rate` - Period rate. e.g=0.0.
        should("test rate") {
            // uncomment below to test the property
            //modelInstance.rate shouldBe ("TODO")
        }

        // to test the property `error` - Dynamic fields will appear.
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

    }
}
