/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.UpdateSystemMeterResponse

class UpdateSystemMeterResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateSystemMeterResponse
        //val modelInstance = UpdateSystemMeterResponse()

        // to test the property `serialNumber` - Meter serial number.
        should("test serialNumber") {
            // uncomment below to test the property
            //modelInstance.serialNumber shouldBe ("TODO")
        }

        // to test the property `manufacturer` - Name of the manufacturer.
        should("test manufacturer") {
            // uncomment below to test the property
            //modelInstance.manufacturer shouldBe ("TODO")
        }

        // to test the property `model` - Model.
        should("test model") {
            // uncomment below to test the property
            //modelInstance.model shouldBe ("TODO")
        }

        // to test the property `type` - Meter type.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `operationalDate` - Operational date.
        should("test operationalDate") {
            // uncomment below to test the property
            //modelInstance.operationalDate shouldBe ("TODO")
        }

    }
}
