/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.UpdateSystemTariffSettingsResponse
import enlighten.commissioning.models.UpdateSystemTariffSettingsResponseTask

class UpdateSystemTariffSettingsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateSystemTariffSettingsResponse
        //val modelInstance = UpdateSystemTariffSettingsResponse()

        // to test the property `task`
        should("test task") {
            // uncomment below to test the property
            //modelInstance.task shouldBe ("TODO")
        }

    }
}
