/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import enlighten.commissioning.models.UpdateSystemTariffSettingsResponseTask

class UpdateSystemTariffSettingsResponseTaskTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateSystemTariffSettingsResponseTask
        //val modelInstance = UpdateSystemTariffSettingsResponseTask()

        // to test the property `status` - Status of latest tariff update task.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `createdAt` - Created time of latest tariff update task.
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

    }
}
