/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Location of the system. Use the ISO 3166-1 2-letter code for the country. Latitude and longitude are calculated by Enlighten, not provided by the client.
 *
 * @param street1 Street line 1.
 * @param street2 Street line 2. This field is optional.
 * @param city City.
 * @param state State.
 * @param country Country.
 * @param postalCode Postal code.
 * @param latitude Latitude.
 * @param longitude Longitude.
 */


data class Address (

    /* Street line 1. */
    @Json(name = "street1")
    val street1: kotlin.String? = null,

    /* Street line 2. This field is optional. */
    @Json(name = "street2")
    val street2: kotlin.String? = null,

    /* City. */
    @Json(name = "city")
    val city: kotlin.String? = null,

    /* State. */
    @Json(name = "state")
    val state: kotlin.String? = null,

    /* Country. */
    @Json(name = "country")
    val country: kotlin.String? = null,

    /* Postal code. */
    @Json(name = "postal_code")
    val postalCode: kotlin.String? = null,

    /* Latitude. */
    @Json(name = "latitude")
    val latitude: kotlin.Int? = null,

    /* Longitude. */
    @Json(name = "longitude")
    val longitude: kotlin.Int? = null

)

