/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import enlighten.commissioning.models.ArrayParamsModulesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param label Name of the array.
 * @param angle Angle of the array. Rotate the array clockwise by the given value.
 * @param tilt Tilt of the array.
 * @param provisionedEnvoy Provisioned envoy.
 * @param left Left axis position of array. Increase the value to move the array to the right, and decrease to move it to the left.
 * @param top Top axis position of array. Increase the value to move the array up, and decrease to move it down.
 * @param modules 
 * @param id ID of the array. ID cannot be changed. It is only used to identify the array that needs to be updated.
 */


data class ArrayParams (

    /* Name of the array. */
    @Json(name = "label")
    val label: kotlin.String,

    /* Angle of the array. Rotate the array clockwise by the given value. */
    @Json(name = "angle")
    val angle: kotlin.Int,

    /* Tilt of the array. */
    @Json(name = "tilt")
    val tilt: kotlin.String,

    /* Provisioned envoy. */
    @Json(name = "provisioned_envoy")
    val provisionedEnvoy: kotlin.String,

    /* Left axis position of array. Increase the value to move the array to the right, and decrease to move it to the left. */
    @Json(name = "left")
    val left: kotlin.Int,

    /* Top axis position of array. Increase the value to move the array up, and decrease to move it down. */
    @Json(name = "top")
    val top: kotlin.Int,

    @Json(name = "modules")
    val modules: kotlin.collections.List<ArrayParamsModulesInner>,

    /* ID of the array. ID cannot be changed. It is only used to identify the array that needs to be updated. */
    @Json(name = "id")
    val id: kotlin.Int? = null

)

