/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param left Left axis position of module w.r.t Array. Increase the value to move the module to the right, and decrease to move it to the left.
 * @param top Top axis position of module w.r.t Array. Increase the value to move the module up, and decrease to move it down.
 * @param angle Angle of the module. Rotate the module clockwise by the given value w.r.t array angle. For example to rotate the array clockwise by 90 degrees pass 90.
 * @param serialNum Inverter serial number mapped with this module.
 * @param id ID of the module. ID cannot be changed. It is only used to identify the array that needs to be updated.
 */


data class ArrayParamsModulesInner (

    /* Left axis position of module w.r.t Array. Increase the value to move the module to the right, and decrease to move it to the left. */
    @Json(name = "left")
    val left: kotlin.Int,

    /* Top axis position of module w.r.t Array. Increase the value to move the module up, and decrease to move it down. */
    @Json(name = "top")
    val top: kotlin.Int,

    /* Angle of the module. Rotate the module clockwise by the given value w.r.t array angle. For example to rotate the array clockwise by 90 degrees pass 90. */
    @Json(name = "angle")
    val angle: kotlin.Int,

    /* Inverter serial number mapped with this module. */
    @Json(name = "serial_num")
    val serialNum: kotlin.String,

    /* ID of the module. ID cannot be changed. It is only used to identify the array that needs to be updated. */
    @Json(name = "id")
    val id: kotlin.Int? = null

)

