/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import enlighten.commissioning.models.CompanyRoleEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Name of the system owner. Owner must be an Enlighten user. If the user of the API is a self-installer, the owner must be himself. If the query parameter 'expand=owner' passed in the request owner detail will appear in the response.
 *
 * @param companyId Enlighten-generated ID of the company to which the user belongs.
 * @param companyName Name of the company to which the user belongs.
 * @param location Company location.
 * @param roles What type of company this is in Enphase. For installer company roles will be ['installer']. For other role roles will be empty.
 * @param uri URI to the show() method for the company. System-generated.
 */


data class Company (

    /* Enlighten-generated ID of the company to which the user belongs. */
    @Json(name = "company_id")
    val companyId: kotlin.Int? = null,

    /* Name of the company to which the user belongs. */
    @Json(name = "company_name")
    val companyName: kotlin.String? = null,

    /* Company location. */
    @Json(name = "location")
    val location: kotlin.String? = null,

    /* What type of company this is in Enphase. For installer company roles will be ['installer']. For other role roles will be empty. */
    @Json(name = "roles")
    val roles: kotlin.collections.List<CompanyRoleEnum>? = null,

    /* URI to the show() method for the company. System-generated. */
    @Json(name = "uri")
    val uri: kotlin.String? = null

)

