/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import enlighten.commissioning.models.GetGridProfilesResponseGridProfilesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param gridProfiles 
 */


data class GetGridProfilesResponse (

    @Json(name = "grid_profiles")
    val gridProfiles: kotlin.collections.List<GetGridProfilesResponseGridProfilesInner>? = null

)

