/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Information about the manufacturer whose PV module models are in the response.
 *
 * @param pvManufacturerId Pv manufacturer ID.
 * @param name Name of the Pv manufacturer.
 */


data class GetPvManufacturerModelsResponsePvManufacturers (

    /* Pv manufacturer ID. */
    @Json(name = "pv_manufacturer_id")
    val pvManufacturerId: kotlin.Int? = null,

    /* Name of the Pv manufacturer. */
    @Json(name = "name")
    val name: kotlin.String? = null

)

