/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param authorizedSubcontractorId The Enlighten ID of the sub-contractor of this system. System-generated.
 * @param authorizedSubcontractorName Name of the sub-contractor of this system.
 * @param status Current status of the subcontractor for the site. This field will be shown only for pending and rejected sub-contractors.
 */


data class GetPartnerActivationsResponseSystemsInnerAuthorizedSubcontractorsInner (

    /* The Enlighten ID of the sub-contractor of this system. System-generated. */
    @Json(name = "authorized_subcontractor_id")
    val authorizedSubcontractorId: kotlin.Int? = null,

    /* Name of the sub-contractor of this system. */
    @Json(name = "authorized_subcontractor_name")
    val authorizedSubcontractorName: kotlin.String? = null,

    /* Current status of the subcontractor for the site. This field will be shown only for pending and rejected sub-contractors. */
    @Json(name = "status")
    val status: kotlin.String? = null

)

