/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import enlighten.commissioning.models.GetSelfCompanyAuthorizedSubcontractorsResponseAuthorizedSubcontractorsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param companyId Enlighten ID of the API user's company.
 * @param companyName Name of the API user's company.
 * @param authorizedSubcontractors A list of subcontractors belonging to the API user's company. May be empty.
 */


data class GetSelfCompanyAuthorizedSubcontractorsResponse (

    /* Enlighten ID of the API user's company. */
    @Json(name = "company_id")
    val companyId: kotlin.Int? = null,

    /* Name of the API user's company. */
    @Json(name = "company_name")
    val companyName: kotlin.String? = null,

    /* A list of subcontractors belonging to the API user's company. May be empty. */
    @Json(name = "authorized_subcontractors")
    val authorizedSubcontractors: kotlin.collections.List<GetSelfCompanyAuthorizedSubcontractorsResponseAuthorizedSubcontractorsInner>? = null

)

