/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userId Enlighten ID of the user.
 * @param companyId Enlighten ID of the company that the user belongs to. If the user does not belong to a company, this field will not be present in the response.
 */


data class SearchUsersResponse (

    /* Enlighten ID of the user. */
    @Json(name = "user_id")
    val userId: kotlin.Int? = null,

    /* Enlighten ID of the company that the user belongs to. If the user does not belong to a company, this field will not be present in the response. */
    @Json(name = "company_id")
    val companyId: kotlin.Int? = null

)

