/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * How the system's Envoys connect to the Internet. Use 'dialup' if the Internet connection is satellite or dial-up.
 *
 * Values: none,cellular,broadband,dialup
 */

@JsonClass(generateAdapter = false)
enum class SystemInternetConnectionEnum(val value: kotlin.String) {

    @Json(name = "none")
    none("none"),

    @Json(name = "cellular")
    cellular("cellular"),

    @Json(name = "broadband")
    broadband("broadband"),

    @Json(name = "dialup")
    dialup("dialup");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SystemInternetConnectionEnum) "$data" else null

        /**
         * Returns a valid [SystemInternetConnectionEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SystemInternetConnectionEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

