/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import enlighten.commissioning.models.SystemArrayModulesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id ID of the array.
 * @param label Name of the array.
 * @param angle Angle of the array.
 * @param tilt Tilt of the array.
 * @param reportingEnvoys List of envoys serial numbers.
 * @param provisionedEnvoy Provisioned envoy.
 * @param updatedAt Last updated Epoch time.
 * @param left Left axis position of array.
 * @param top Top axis position of array.
 * @param modules 
 */


data class SystemArray (

    /* ID of the array. */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* Name of the array. */
    @Json(name = "label")
    val label: kotlin.String? = null,

    /* Angle of the array. */
    @Json(name = "angle")
    val angle: kotlin.Int? = null,

    /* Tilt of the array. */
    @Json(name = "tilt")
    val tilt: kotlin.String? = null,

    /* List of envoys serial numbers. */
    @Json(name = "reporting_envoys")
    val reportingEnvoys: kotlin.collections.List<kotlin.String>? = null,

    /* Provisioned envoy. */
    @Json(name = "provisioned_envoy")
    val provisionedEnvoy: kotlin.String? = null,

    /* Last updated Epoch time. */
    @Json(name = "updated_at")
    val updatedAt: kotlin.Long? = null,

    /* Left axis position of array. */
    @Json(name = "left")
    val left: kotlin.Int? = null,

    /* Top axis position of array. */
    @Json(name = "top")
    val top: kotlin.Int? = null,

    @Json(name = "modules")
    val modules: kotlin.collections.List<SystemArrayModulesInner>? = null

)

