/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: _1,_2,_3,_4,_5,in_progress
 */

@JsonClass(generateAdapter = false)
enum class SystemStageEnum(val value: kotlin.String) {

    @Json(name = "1")
    _1("1"),

    @Json(name = "2")
    _2("2"),

    @Json(name = "3")
    _3("3"),

    @Json(name = "4")
    _4("4"),

    @Json(name = "5")
    _5("5"),

    @Json(name = "in_progress")
    in_progress("in_progress");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SystemStageEnum) "$data" else null

        /**
         * Returns a valid [SystemStageEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SystemStageEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

