/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param envoySerialNumber Envoy serial number.
 * @param enpowerSerialNumbers Enpower serial numbers.
 */


data class SystemParamsEnpowerInner (

    /* Envoy serial number. */
    @Json(name = "envoy_serial_number")
    val envoySerialNumber: kotlin.String? = null,

    /* Enpower serial numbers. */
    @Json(name = "enpower_serial_numbers")
    val enpowerSerialNumbers: kotlin.collections.List<kotlin.String>? = null

)

