/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models

import enlighten.commissioning.models.TariffSettingsTariff
import enlighten.commissioning.models.UpdateSystemTariffSettingsResponseTask

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param tariff 
 * @param task 
 */


data class TariffSettings (

    @Json(name = "tariff")
    val tariff: TariffSettingsTariff? = null,

    @Json(name = "task")
    val task: UpdateSystemTariffSettingsResponseTask? = null

)

