/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Single rate.
 *
 * @param rate Usage rate. e.g=0.0.
 * @param sell FiT rate. e.g=0.0.
 */


data class TariffSettingsTariffSingleRate (

    /* Usage rate. e.g=0.0. */
    @Json(name = "rate")
    val rate: kotlin.String? = null,

    /* FiT rate. e.g=0.0. */
    @Json(name = "sell")
    val sell: kotlin.String? = null

)

