/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package enlighten.commissioning.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param errorCode 
 * @param errorMessages 
 */


data class UnprocessableEntityError (

    @Json(name = "errorCode")
    val errorCode: kotlin.Int? = null,

    @Json(name = "errorMessages")
    val errorMessages: kotlin.collections.List<kotlin.String>? = null

)

